//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientpharmacieWPF.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/Wcf_Pharmacie")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Client", Namespace="http://schemas.datacontract.org/2004/07/Wcf_Pharmacie")]
    [System.SerializableAttribute()]
    public partial class Client : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientpharmacieWPF.ServiceReference1.Commande[] CommandesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_clientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string prenomField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientpharmacieWPF.ServiceReference1.Commande[] Commandes {
            get {
                return this.CommandesField;
            }
            set {
                if ((object.ReferenceEquals(this.CommandesField, value) != true)) {
                    this.CommandesField = value;
                    this.RaisePropertyChanged("Commandes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_client {
            get {
                return this.id_clientField;
            }
            set {
                if ((this.id_clientField.Equals(value) != true)) {
                    this.id_clientField = value;
                    this.RaisePropertyChanged("id_client");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nom {
            get {
                return this.nomField;
            }
            set {
                if ((object.ReferenceEquals(this.nomField, value) != true)) {
                    this.nomField = value;
                    this.RaisePropertyChanged("nom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string prenom {
            get {
                return this.prenomField;
            }
            set {
                if ((object.ReferenceEquals(this.prenomField, value) != true)) {
                    this.prenomField = value;
                    this.RaisePropertyChanged("prenom");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Commande", Namespace="http://schemas.datacontract.org/2004/07/Wcf_Pharmacie")]
    [System.SerializableAttribute()]
    public partial class Commande : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientpharmacieWPF.ServiceReference1.Achat[] AchatsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientpharmacieWPF.ServiceReference1.Client ClientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string heure_commandeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> id_clientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_commandeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string statut_commandeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string statut_livraisonField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientpharmacieWPF.ServiceReference1.Achat[] Achats {
            get {
                return this.AchatsField;
            }
            set {
                if ((object.ReferenceEquals(this.AchatsField, value) != true)) {
                    this.AchatsField = value;
                    this.RaisePropertyChanged("Achats");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientpharmacieWPF.ServiceReference1.Client Client {
            get {
                return this.ClientField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientField, value) != true)) {
                    this.ClientField = value;
                    this.RaisePropertyChanged("Client");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string heure_commande {
            get {
                return this.heure_commandeField;
            }
            set {
                if ((object.ReferenceEquals(this.heure_commandeField, value) != true)) {
                    this.heure_commandeField = value;
                    this.RaisePropertyChanged("heure_commande");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> id_client {
            get {
                return this.id_clientField;
            }
            set {
                if ((this.id_clientField.Equals(value) != true)) {
                    this.id_clientField = value;
                    this.RaisePropertyChanged("id_client");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_commande {
            get {
                return this.id_commandeField;
            }
            set {
                if ((this.id_commandeField.Equals(value) != true)) {
                    this.id_commandeField = value;
                    this.RaisePropertyChanged("id_commande");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string statut_commande {
            get {
                return this.statut_commandeField;
            }
            set {
                if ((object.ReferenceEquals(this.statut_commandeField, value) != true)) {
                    this.statut_commandeField = value;
                    this.RaisePropertyChanged("statut_commande");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string statut_livraison {
            get {
                return this.statut_livraisonField;
            }
            set {
                if ((object.ReferenceEquals(this.statut_livraisonField, value) != true)) {
                    this.statut_livraisonField = value;
                    this.RaisePropertyChanged("statut_livraison");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Achat", Namespace="http://schemas.datacontract.org/2004/07/Wcf_Pharmacie")]
    [System.SerializableAttribute()]
    public partial class Achat : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientpharmacieWPF.ServiceReference1.Commande CommandeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientpharmacieWPF.ServiceReference1.Stock StockField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_achatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_commandeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> id_stockField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> prix_totalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> quantitéField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientpharmacieWPF.ServiceReference1.Commande Commande {
            get {
                return this.CommandeField;
            }
            set {
                if ((object.ReferenceEquals(this.CommandeField, value) != true)) {
                    this.CommandeField = value;
                    this.RaisePropertyChanged("Commande");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientpharmacieWPF.ServiceReference1.Stock Stock {
            get {
                return this.StockField;
            }
            set {
                if ((object.ReferenceEquals(this.StockField, value) != true)) {
                    this.StockField = value;
                    this.RaisePropertyChanged("Stock");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_achat {
            get {
                return this.id_achatField;
            }
            set {
                if ((this.id_achatField.Equals(value) != true)) {
                    this.id_achatField = value;
                    this.RaisePropertyChanged("id_achat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_commande {
            get {
                return this.id_commandeField;
            }
            set {
                if ((this.id_commandeField.Equals(value) != true)) {
                    this.id_commandeField = value;
                    this.RaisePropertyChanged("id_commande");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> id_stock {
            get {
                return this.id_stockField;
            }
            set {
                if ((this.id_stockField.Equals(value) != true)) {
                    this.id_stockField = value;
                    this.RaisePropertyChanged("id_stock");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> prix_total {
            get {
                return this.prix_totalField;
            }
            set {
                if ((this.prix_totalField.Equals(value) != true)) {
                    this.prix_totalField = value;
                    this.RaisePropertyChanged("prix_total");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> quantité {
            get {
                return this.quantitéField;
            }
            set {
                if ((this.quantitéField.Equals(value) != true)) {
                    this.quantitéField = value;
                    this.RaisePropertyChanged("quantité");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Stock", Namespace="http://schemas.datacontract.org/2004/07/Wcf_Pharmacie")]
    [System.SerializableAttribute()]
    public partial class Stock : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientpharmacieWPF.ServiceReference1.Achat[] AchatsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientpharmacieWPF.ServiceReference1.Produit[] ProduitsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_stockField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] image_ProduitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string image_testField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nom_produit_stockField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> quantite_produitField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientpharmacieWPF.ServiceReference1.Achat[] Achats {
            get {
                return this.AchatsField;
            }
            set {
                if ((object.ReferenceEquals(this.AchatsField, value) != true)) {
                    this.AchatsField = value;
                    this.RaisePropertyChanged("Achats");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientpharmacieWPF.ServiceReference1.Produit[] Produits {
            get {
                return this.ProduitsField;
            }
            set {
                if ((object.ReferenceEquals(this.ProduitsField, value) != true)) {
                    this.ProduitsField = value;
                    this.RaisePropertyChanged("Produits");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_stock {
            get {
                return this.id_stockField;
            }
            set {
                if ((this.id_stockField.Equals(value) != true)) {
                    this.id_stockField = value;
                    this.RaisePropertyChanged("id_stock");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] image_Produit {
            get {
                return this.image_ProduitField;
            }
            set {
                if ((object.ReferenceEquals(this.image_ProduitField, value) != true)) {
                    this.image_ProduitField = value;
                    this.RaisePropertyChanged("image_Produit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string image_test {
            get {
                return this.image_testField;
            }
            set {
                if ((object.ReferenceEquals(this.image_testField, value) != true)) {
                    this.image_testField = value;
                    this.RaisePropertyChanged("image_test");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nom_produit_stock {
            get {
                return this.nom_produit_stockField;
            }
            set {
                if ((object.ReferenceEquals(this.nom_produit_stockField, value) != true)) {
                    this.nom_produit_stockField = value;
                    this.RaisePropertyChanged("nom_produit_stock");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> quantite_produit {
            get {
                return this.quantite_produitField;
            }
            set {
                if ((this.quantite_produitField.Equals(value) != true)) {
                    this.quantite_produitField = value;
                    this.RaisePropertyChanged("quantite_produit");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Produit", Namespace="http://schemas.datacontract.org/2004/07/Wcf_Pharmacie")]
    [System.SerializableAttribute()]
    public partial class Produit : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientpharmacieWPF.ServiceReference1.Stock StockField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string date_heure_ajout_produitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_produitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> id_stockField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nom_produitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> prix_uniteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> quantiteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientpharmacieWPF.ServiceReference1.Stock Stock {
            get {
                return this.StockField;
            }
            set {
                if ((object.ReferenceEquals(this.StockField, value) != true)) {
                    this.StockField = value;
                    this.RaisePropertyChanged("Stock");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string date_heure_ajout_produit {
            get {
                return this.date_heure_ajout_produitField;
            }
            set {
                if ((object.ReferenceEquals(this.date_heure_ajout_produitField, value) != true)) {
                    this.date_heure_ajout_produitField = value;
                    this.RaisePropertyChanged("date_heure_ajout_produit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_produit {
            get {
                return this.id_produitField;
            }
            set {
                if ((this.id_produitField.Equals(value) != true)) {
                    this.id_produitField = value;
                    this.RaisePropertyChanged("id_produit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> id_stock {
            get {
                return this.id_stockField;
            }
            set {
                if ((this.id_stockField.Equals(value) != true)) {
                    this.id_stockField = value;
                    this.RaisePropertyChanged("id_stock");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nom_produit {
            get {
                return this.nom_produitField;
            }
            set {
                if ((object.ReferenceEquals(this.nom_produitField, value) != true)) {
                    this.nom_produitField = value;
                    this.RaisePropertyChanged("nom_produit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> prix_unite {
            get {
                return this.prix_uniteField;
            }
            set {
                if ((this.prix_uniteField.Equals(value) != true)) {
                    this.prix_uniteField = value;
                    this.RaisePropertyChanged("prix_unite");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> quantite {
            get {
                return this.quantiteField;
            }
            set {
                if ((this.quantiteField.Equals(value) != true)) {
                    this.quantiteField = value;
                    this.RaisePropertyChanged("quantite");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProduitReturn", Namespace="http://schemas.datacontract.org/2004/07/Wcf_Pharmacie")]
    [System.SerializableAttribute()]
    public partial class ProduitReturn : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientpharmacieWPF.ServiceReference1.Achat[] AchatsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientpharmacieWPF.ServiceReference1.Produit[] ProduitsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_stockField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] image_ProduitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string image_testField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nom_produit_stockField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> quantite_produitField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientpharmacieWPF.ServiceReference1.Achat[] Achats {
            get {
                return this.AchatsField;
            }
            set {
                if ((object.ReferenceEquals(this.AchatsField, value) != true)) {
                    this.AchatsField = value;
                    this.RaisePropertyChanged("Achats");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientpharmacieWPF.ServiceReference1.Produit[] Produits {
            get {
                return this.ProduitsField;
            }
            set {
                if ((object.ReferenceEquals(this.ProduitsField, value) != true)) {
                    this.ProduitsField = value;
                    this.RaisePropertyChanged("Produits");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_stock {
            get {
                return this.id_stockField;
            }
            set {
                if ((this.id_stockField.Equals(value) != true)) {
                    this.id_stockField = value;
                    this.RaisePropertyChanged("id_stock");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] image_Produit {
            get {
                return this.image_ProduitField;
            }
            set {
                if ((object.ReferenceEquals(this.image_ProduitField, value) != true)) {
                    this.image_ProduitField = value;
                    this.RaisePropertyChanged("image_Produit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string image_test {
            get {
                return this.image_testField;
            }
            set {
                if ((object.ReferenceEquals(this.image_testField, value) != true)) {
                    this.image_testField = value;
                    this.RaisePropertyChanged("image_test");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nom_produit_stock {
            get {
                return this.nom_produit_stockField;
            }
            set {
                if ((object.ReferenceEquals(this.nom_produit_stockField, value) != true)) {
                    this.nom_produit_stockField = value;
                    this.RaisePropertyChanged("nom_produit_stock");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> quantite_produit {
            get {
                return this.quantite_produitField;
            }
            set {
                if ((this.quantite_produitField.Equals(value) != true)) {
                    this.quantite_produitField = value;
                    this.RaisePropertyChanged("quantite_produit");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClientReturn", Namespace="http://schemas.datacontract.org/2004/07/Wcf_Pharmacie")]
    [System.SerializableAttribute()]
    public partial class ClientReturn : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientpharmacieWPF.ServiceReference1.Achat[] AchatsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientpharmacieWPF.ServiceReference1.Produit[] ProduitsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_clientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string prenomField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientpharmacieWPF.ServiceReference1.Achat[] Achats {
            get {
                return this.AchatsField;
            }
            set {
                if ((object.ReferenceEquals(this.AchatsField, value) != true)) {
                    this.AchatsField = value;
                    this.RaisePropertyChanged("Achats");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientpharmacieWPF.ServiceReference1.Produit[] Produits {
            get {
                return this.ProduitsField;
            }
            set {
                if ((object.ReferenceEquals(this.ProduitsField, value) != true)) {
                    this.ProduitsField = value;
                    this.RaisePropertyChanged("Produits");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_client {
            get {
                return this.id_clientField;
            }
            set {
                if ((this.id_clientField.Equals(value) != true)) {
                    this.id_clientField = value;
                    this.RaisePropertyChanged("id_client");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nom {
            get {
                return this.nomField;
            }
            set {
                if ((object.ReferenceEquals(this.nomField, value) != true)) {
                    this.nomField = value;
                    this.RaisePropertyChanged("nom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string prenom {
            get {
                return this.prenomField;
            }
            set {
                if ((object.ReferenceEquals(this.prenomField, value) != true)) {
                    this.prenomField = value;
                    this.RaisePropertyChanged("prenom");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="orderHisto", Namespace="http://schemas.datacontract.org/2004/07/Wcf_Pharmacie")]
    [System.SerializableAttribute()]
    public partial class orderHisto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string heureCommandField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nom_ProduitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double prix_Produit_UniteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double prix_totalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int quantiteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string statutLivraisonField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string heureCommand {
            get {
                return this.heureCommandField;
            }
            set {
                if ((object.ReferenceEquals(this.heureCommandField, value) != true)) {
                    this.heureCommandField = value;
                    this.RaisePropertyChanged("heureCommand");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nom_Produit {
            get {
                return this.nom_ProduitField;
            }
            set {
                if ((object.ReferenceEquals(this.nom_ProduitField, value) != true)) {
                    this.nom_ProduitField = value;
                    this.RaisePropertyChanged("nom_Produit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double prix_Produit_Unite {
            get {
                return this.prix_Produit_UniteField;
            }
            set {
                if ((this.prix_Produit_UniteField.Equals(value) != true)) {
                    this.prix_Produit_UniteField = value;
                    this.RaisePropertyChanged("prix_Produit_Unite");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double prix_total {
            get {
                return this.prix_totalField;
            }
            set {
                if ((this.prix_totalField.Equals(value) != true)) {
                    this.prix_totalField = value;
                    this.RaisePropertyChanged("prix_total");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int quantite {
            get {
                return this.quantiteField;
            }
            set {
                if ((this.quantiteField.Equals(value) != true)) {
                    this.quantiteField = value;
                    this.RaisePropertyChanged("quantite");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string statutLivraison {
            get {
                return this.statutLivraisonField;
            }
            set {
                if ((object.ReferenceEquals(this.statutLivraisonField, value) != true)) {
                    this.statutLivraisonField = value;
                    this.RaisePropertyChanged("statutLivraison");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        ClientpharmacieWPF.ServiceReference1.CompositeType GetDataUsingDataContract(ClientpharmacieWPF.ServiceReference1.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<ClientpharmacieWPF.ServiceReference1.CompositeType> GetDataUsingDataContractAsync(ClientpharmacieWPF.ServiceReference1.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ajouterclients", ReplyAction="http://tempuri.org/IService1/ajouterclientsResponse")]
        string ajouterclients(ClientpharmacieWPF.ServiceReference1.Client client);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ajouterclients", ReplyAction="http://tempuri.org/IService1/ajouterclientsResponse")]
        System.Threading.Tasks.Task<string> ajouterclientsAsync(ClientpharmacieWPF.ServiceReference1.Client client);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/verifierClients", ReplyAction="http://tempuri.org/IService1/verifierClientsResponse")]
        bool verifierClients(string email, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/verifierClients", ReplyAction="http://tempuri.org/IService1/verifierClientsResponse")]
        System.Threading.Tasks.Task<bool> verifierClientsAsync(string email, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/listeProduit", ReplyAction="http://tempuri.org/IService1/listeProduitResponse")]
        ClientpharmacieWPF.ServiceReference1.ProduitReturn[] listeProduit();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/listeProduit", ReplyAction="http://tempuri.org/IService1/listeProduitResponse")]
        System.Threading.Tasks.Task<ClientpharmacieWPF.ServiceReference1.ProduitReturn[]> listeProduitAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/passerCommande", ReplyAction="http://tempuri.org/IService1/passerCommandeResponse")]
        string passerCommande(string nomclient, string nomproduit, int quantité);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/passerCommande", ReplyAction="http://tempuri.org/IService1/passerCommandeResponse")]
        System.Threading.Tasks.Task<string> passerCommandeAsync(string nomclient, string nomproduit, int quantité);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/recupereParEmail", ReplyAction="http://tempuri.org/IService1/recupereParEmailResponse")]
        ClientpharmacieWPF.ServiceReference1.ClientReturn recupereParEmail(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/recupereParEmail", ReplyAction="http://tempuri.org/IService1/recupereParEmailResponse")]
        System.Threading.Tasks.Task<ClientpharmacieWPF.ServiceReference1.ClientReturn> recupereParEmailAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/modifierClients", ReplyAction="http://tempuri.org/IService1/modifierClientsResponse")]
        string modifierClients(ClientpharmacieWPF.ServiceReference1.ClientReturn client);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/modifierClients", ReplyAction="http://tempuri.org/IService1/modifierClientsResponse")]
        System.Threading.Tasks.Task<string> modifierClientsAsync(ClientpharmacieWPF.ServiceReference1.ClientReturn client);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/supprimerClients", ReplyAction="http://tempuri.org/IService1/supprimerClientsResponse")]
        string supprimerClients(ClientpharmacieWPF.ServiceReference1.ClientReturn client);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/supprimerClients", ReplyAction="http://tempuri.org/IService1/supprimerClientsResponse")]
        System.Threading.Tasks.Task<string> supprimerClientsAsync(ClientpharmacieWPF.ServiceReference1.ClientReturn client);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getcommandehisto", ReplyAction="http://tempuri.org/IService1/getcommandehistoResponse")]
        ClientpharmacieWPF.ServiceReference1.orderHisto[] getcommandehisto(ClientpharmacieWPF.ServiceReference1.ClientReturn client);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getcommandehisto", ReplyAction="http://tempuri.org/IService1/getcommandehistoResponse")]
        System.Threading.Tasks.Task<ClientpharmacieWPF.ServiceReference1.orderHisto[]> getcommandehistoAsync(ClientpharmacieWPF.ServiceReference1.ClientReturn client);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : ClientpharmacieWPF.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ClientpharmacieWPF.ServiceReference1.IService1>, ClientpharmacieWPF.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public ClientpharmacieWPF.ServiceReference1.CompositeType GetDataUsingDataContract(ClientpharmacieWPF.ServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<ClientpharmacieWPF.ServiceReference1.CompositeType> GetDataUsingDataContractAsync(ClientpharmacieWPF.ServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public string ajouterclients(ClientpharmacieWPF.ServiceReference1.Client client) {
            return base.Channel.ajouterclients(client);
        }
        
        public System.Threading.Tasks.Task<string> ajouterclientsAsync(ClientpharmacieWPF.ServiceReference1.Client client) {
            return base.Channel.ajouterclientsAsync(client);
        }
        
        public bool verifierClients(string email, string pass) {
            return base.Channel.verifierClients(email, pass);
        }
        
        public System.Threading.Tasks.Task<bool> verifierClientsAsync(string email, string pass) {
            return base.Channel.verifierClientsAsync(email, pass);
        }
        
        public ClientpharmacieWPF.ServiceReference1.ProduitReturn[] listeProduit() {
            return base.Channel.listeProduit();
        }
        
        public System.Threading.Tasks.Task<ClientpharmacieWPF.ServiceReference1.ProduitReturn[]> listeProduitAsync() {
            return base.Channel.listeProduitAsync();
        }
        
        public string passerCommande(string nomclient, string nomproduit, int quantité) {
            return base.Channel.passerCommande(nomclient, nomproduit, quantité);
        }
        
        public System.Threading.Tasks.Task<string> passerCommandeAsync(string nomclient, string nomproduit, int quantité) {
            return base.Channel.passerCommandeAsync(nomclient, nomproduit, quantité);
        }
        
        public ClientpharmacieWPF.ServiceReference1.ClientReturn recupereParEmail(string email) {
            return base.Channel.recupereParEmail(email);
        }
        
        public System.Threading.Tasks.Task<ClientpharmacieWPF.ServiceReference1.ClientReturn> recupereParEmailAsync(string email) {
            return base.Channel.recupereParEmailAsync(email);
        }
        
        public string modifierClients(ClientpharmacieWPF.ServiceReference1.ClientReturn client) {
            return base.Channel.modifierClients(client);
        }
        
        public System.Threading.Tasks.Task<string> modifierClientsAsync(ClientpharmacieWPF.ServiceReference1.ClientReturn client) {
            return base.Channel.modifierClientsAsync(client);
        }
        
        public string supprimerClients(ClientpharmacieWPF.ServiceReference1.ClientReturn client) {
            return base.Channel.supprimerClients(client);
        }
        
        public System.Threading.Tasks.Task<string> supprimerClientsAsync(ClientpharmacieWPF.ServiceReference1.ClientReturn client) {
            return base.Channel.supprimerClientsAsync(client);
        }
        
        public ClientpharmacieWPF.ServiceReference1.orderHisto[] getcommandehisto(ClientpharmacieWPF.ServiceReference1.ClientReturn client) {
            return base.Channel.getcommandehisto(client);
        }
        
        public System.Threading.Tasks.Task<ClientpharmacieWPF.ServiceReference1.orderHisto[]> getcommandehistoAsync(ClientpharmacieWPF.ServiceReference1.ClientReturn client) {
            return base.Channel.getcommandehistoAsync(client);
        }
    }
}
